module.exports = {

DUPLICATE_ID: "이미 존재하는 ID 입니다.",
DUPLICATE_NICKNAME: "이미 존재하는 닉네임 입니다.",
HASHING_FAIL: "패시워드를 해싱하는 과정에서 오류가 났습니다.",
NULL_VALUE: "필요한 값이 없습니다",
OUT_OF_VALUE: "파라미터 값이 잘못되었습니다",
ALREADY_USER: "이미 있는 ID 입니다.",
SIGNUP_SUCCESS: "회원가입 성공했습니다.",
ID_OR_PW_WRO_VALUE: "아이디/비밀번호 값이 잘못됬습니다.",
LOGIN_SUCCESS: "로그인 성공",
DB_ERR: "데이터베이스 에러",
WRONG_TABLE_PW: "게시물 비밀번호가 일치하지 않습니다.",
CREATE_TOKEN: "토큰이 발급 되었습니다",
REFRESH_TOKEN: "토큰이 재 발급 되었습니다",
EMPTY_TOKEN: "헤더에 토큰이 없습니다.",
EXPRIED_TOKEN: "토큰이 만기 되었습니다",
INVALID_TOKEN: "토큰이 유효하지 않습니다.",
SEARCH_MAIN_INFO_SUCCESS: "메인 엑티비티 필요 정보 조회 성공",
MEMBERSHIP_INSERT_FAIL: "인서트 실패",
MEMBERSHIP_INSERT_SUCCESS: "인서트 성공",
CREATE_CHALLENGE_SUCCESS : "챌린지 개설 건의 성공했습니다.",
SEARCH_TOP10_CHALLENGE_LIST_SUCCESS : "top10 챌린지 리스트 조회 성공했습니다.",
SEARCH_BOOKMARK_CHALLENGE_LIST_SUCCESS : "즐켜찾기 챌린지 리스트 조히 성공했습니다.",
SEARCH_TOGETHER_CHALLENGE_LIST_SUCCESS : "함께하기 챌린지 리스트 조히 성공했습니다.",
INSERT_TOGETHER_CHALLENGE_SUCCESS : "함께하기 챌린지 추가 성공했습니다.",
DELETE_TOGETHER_CHALLENGE_SUCCESS : "함께하기 챌린지 삭제 성공했습니다.",
UPDATE_BOOKMARK_CHALLENGE_SUCCESS : "즐겨찾기 챌린지 순서 변경 성공했습니다.",

  DUPLICATE_ID: "이미 존재하는 ID 입니다.",
  DUPLICATE_NICKNAME: "이미 존재하는 닉네임 입니다.",
  HASHING_FAIL: "패시워드를 해싱하는 과정에서 오류가 났습니다.",
  GET_USER_DATA_SUCCESS: "유저의 정보 조회 성공",

  NULL_VALUE: "필요한 값이 없습니다",
  OUT_OF_VALUE: "파라미터 값이 잘못되었습니다",
  ALREADY_USER: "이미 있는 ID 입니다.",

  SIGNUP_SUCCESS: "회원가입 성공했습니다.",
  SIGNIN_SUCCESS: "로그인 성공.",

  ID_OR_PW_WRO_VALUE: "아이디/비밀번호 값이 잘못됬습니다.",
  LOGIN_SUCCESS: "로그인 성공",
  DB_ERR: "데이터베이스 에러",
  WRONG_TABLE_PW: "게시물 비밀번호가 일치하지 않습니다.",

  CREATE_TOKEN: "토큰이 발급 되었습니다",
  REFRESH_TOKEN: "토큰이 재 발급 되었습니다",
  EMPTY_TOKEN: "헤더에 토큰이 없습니다.",
  EXPRIED_TOKEN: "토큰이 만기 되었습니다",
  INVALID_TOKEN: "토큰이 유효하지 않습니다.",

  SEARCH_MAIN_INFO_SUCCESS: "메인 엑티비티 필요 정보 조회 성공",
  INSERT_LIKE: "좋아요를 하였습니다.",
  DELETE_LIKE: "좋아요를 취소하였습니다",
  MEMBERSHIP_INSERT_FAIL: "인서트 실패",
  MEMBERSHIP_INSERT_SUCCESS: "인서트 성공",
  CREATE_CHALLENGE_SUCCESS: "챌린지 개설 건의 성공했습니다.",
  SEARCH_TOP10_CHALLENGE_LIST_SUCCESS: "top10 챌린지 리스트 조회 성공했습니다.",
  SEARCH_BOOKMARK_CHALLENGE_LIST_SUCCESS: "즐켜찾기 챌린지 리스트 조히 성공했습니다.",
  GET_SUMMARY_SUCCESS: "어스 정보 조회 성공",
  GET_KEYWORDS_SUCCESS: "검색 키워드 리스트 조회 성공",
  GET_CHALLENGE_DETAIL_SUCCESS: "챌린지 상세보기 성공",
  CREATE_COMMENT_SUCCESS: "챌린지 한줄 응원 등록 성공",
  GET_COMMENT_SUCCESS: "챌린지 한줄 응원 리스트 조회 성공",
  GET_TIMELINE_SUCCESS: "유저의 타임라인 조회 성공"

};
